### ISSUE TITLE
Get challenge -> expire -> withdraw working

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#81] opened 2019-01-26 19:01 UTC
#### RPS and TTT

For Player A (Xs) and Player B (Os).

#### TTT
Possibly also for Player A (Os) and Player B (Xs).

**Comment by geoknee** [comment] 2019-01-28 22:15
This is apparently a wallet problem.

**Comment by lalexgap** [comment] 2019-01-29 23:18
@geoknee This was caused by the wallet hiding itself after a challenge expiry is acknowledged. This is now fixed in the `wallet` and now works for `rps`. I'll leave this open for `ttt`

**Closed** 2019-01-30 08:54 UTC
Labels: ttt
